# Atom Tracker Configuration
model_type: "atom_tracker"
hidden_size: 256
num_layers: 6
num_heads: 8
num_atom_types: 118
dropout: 0.1

# Training parameters
batch_size: 32
learning_rate: 0.0001
weight_decay: 0.01
warmup_steps: 1000
max_steps: 100000 