# City Reconstruction Configuration
model_type: "city_reconstruction"
hidden_dim: 256
num_heads: 8
dropout: 0.1

# Point Cloud Processing
point_cloud_size: 8192
point_features: 32

# Mesh Generation
mesh_resolution: 256
uv_resolution: 1024

# Training Configuration
batch_size: 4
learning_rate: 0.0001
weight_decay: 0.01
warmup_steps: 1000
max_steps: 50000 