# Edge LLM Configuration
model_type: "edge_llm"
vocab_size: 32000
hidden_size: 384
num_layers: 6
num_heads: 6
intermediate_size: 1024
max_seq_length: 512
dropout: 0.1

# Training parameters
batch_size: 1
learning_rate: 0.0001
weight_decay: 0.01
warmup_steps: 100
max_steps: 1000 