# Faster R-CNN Configuration
model_type: "faster_rcnn"
in_channels: 3
base_channels: 64
block_config: [3, 4, 6, 3]
num_classes: 80

# FPN Configuration
fpn_channels: 256
roi_pool_size: 7

# RPN Configuration
anchor_sizes: [32, 64, 128, 256, 512]
anchor_ratios: [0.5, 1.0, 2.0]
rpn_pre_nms_top_n: 2000
rpn_post_nms_top_n: 1000

# Training parameters
batch_size: 16
learning_rate: 0.02
momentum: 0.9
weight_decay: 0.0001
warmup_steps: 500
max_steps: 90000 