# ReID Backbone Configuration
model_type: "reid_backbone"
in_channels: 3
base_channels: 64
feature_dim: 2048

# Architecture
num_blocks: [2, 2, 2, 2]
use_maxpool: true
dropout: 0.1

# Training Configuration
batch_size: 64
learning_rate: 0.0001
weight_decay: 0.0005
warmup_steps: 1000
max_steps: 100000 