# Enhanced ReID Configuration
model_type: "reid"
hidden_dim: 512
feature_dim: 2048
num_heads: 8
bank_size: 10000
num_classes: 1000

# Backbone Configuration
backbone_type: "resnet50"
pretrained: true
last_stride: 1

# Training Configuration
batch_size: 64
learning_rate: 0.00035
weight_decay: 0.0005
warmup_steps: 2000
max_steps: 120000 