# Swin Transformer Configuration
model_type: "swin"
image_size: 224
patch_size: 4
in_channels: 3
embed_dim: 96
depths: [2, 2, 6, 2]
num_heads: [3, 6, 12, 24]
window_size: 7
mlp_ratio: 4.0
dropout: 0.0
num_classes: 1000

# Training parameters
batch_size: 128
learning_rate: 0.0001
weight_decay: 0.05
warmup_steps: 20000
max_steps: 300000 