# Vision Transformer Base Configuration
model_type: "vit"
image_size: 224
patch_size: 16
in_channels: 3
num_classes: 1000
embed_dim: 768
num_layers: 12
num_heads: 12
mlp_ratio: 4
dropout: 0.1

# Training parameters
batch_size: 32
learning_rate: 0.0001
weight_decay: 0.01
warmup_steps: 10000
max_steps: 100000 